networks:
  app_network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
  certs_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certs_data:/etc/nginx/certs  # Mount the certificate volume
      - ./init.sh:/docker-entrypoint.d/init.sh  # Run script to generate certificates on startup
    depends_on:
      - grafana
      - prometheus
      # - loki
      - app
    networks:
      - app_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.55.0
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=15d"]
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    # ports:
      # - "9090:9090"
    networks:
      - app_network
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    # ports:
    #   - "3000:3000"
    networks:
      - app_network
    depends_on:
      - otel-collector
      - prometheus

  # loki:
  #   image: grafana/loki:latest
  #   container_name: loki
  #   volumes:
  #     - ./loki-config.yaml:/mnt/config/loki-config.yaml
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - app_network

  app:
    build: ./app
    # ports:
    #   - "8080:8080"
    networks:
      - app_network
    depends_on:
      - otel-collector
      - prometheus
      - grafana
