networks:
  app_network:
    driver: bridge

volumes:
  prometheus_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - grafana
      - prometheus
      - app
    networks:
      - app_network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.80.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:v2.55.0
    command: ["--config.file=/etc/prometheus/prometheus.yml", "--storage.tsdb.retention.time=15d"]
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:11.3.0
    container_name: grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    networks:
      - app_network
    depends_on:
      - otel-collector
      - prometheus

  app:
    build: ./app
    networks:
      - app_network
    depends_on:
      - otel-collector
      - prometheus
      - grafana
