global:
  query_log_file: /prometheus/query.log
scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:8888"]
      - targets: ["otel-collector:8889"]
